package com.guardtime.container.verification.rule;

public enum RuleType {
    KSIE_FORMAT("KSIE_FORMAT"),
    KSIE_VERIFY_DATA_MANIFEST_EXISTS("KSIE_VERIFY_DATA_MANIFEST_EXISTS"),
    KSIE_VERIFY_DATA_MANIFEST("KSIE_VERIFY_DATA_MANIFEST"),
    KSIE_VERIFY_DATA_EXISTS("KSIE_VERIFY_DATA_EXISTS"),
    KSIE_VERIFY_DATA_HASH("KSIE_VERIFY_DATA_HASH"),
    KSIE_VERIFY_ANNOTATION_MANIFEST_EXISTS("KSIE_VERIFY_ANNOTATION_MANIFEST_EXISTS"),
    KSIE_VERIFY_ANNOTATION_MANIFEST("KSIE_VERIFY_ANNOTATION_MANIFEST"),
    KSIE_VERIFY_ANNOTATION_EXISTS("KSIE_VERIFY_ANNOTATION_EXISTS"),
    KSIE_VERIFY_ANNOTATION("KSIE_VERIFY_ANNOTATION"),
    KSIE_VERIFY_ANNOTATION_DATA_EXISTS("KSIE_VERIFY_ANNOTATION_DATA_EXISTS"),
    KSIE_VERIFY_ANNOTATION_DATA("KSIE_VERIFY_ANNOTATION_DATA"),
    KSIE_VERIFY_MANIFEST("KSIE_VERIFY_MANIFEST"),
    KSIE_VERIFY_SIGNATURE_EXISTS("KSIE_VERIFY_SIGNATURE_EXISTS");

    private final String name;

    RuleType(String name) {
        this.name = name;
    }
}
